config/routes.rb
Rails.application.routes.draw do
  resources :user_transactions
  resources :users
  
  root to: 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :userTransactions, dependent: :destroy
end

app/models/user_transaction.rb
class UserTransaction < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/user_transactions_controller.rb
class UserTransactionsController < ApplicationController
  before_action :set_user_transaction, only: [:show, :edit, :update, :destroy]

  # GET /user_transactions
  # GET /user_transactions.json
  def index
    @user_transactions = UserTransaction.all
  end

  # GET /user_transactions/1
  # GET /user_transactions/1.json
  def show
  end

  # GET /user_transactions/new
  def new
    @user_transaction = UserTransaction.new
    @user_options = User.all.map {|u|[u.name, u.id]}
  end

  # GET /user_transactions/1/edit
  def edit
  end

  # POST /user_transactions
  # POST /user_transactions.json
  def create
    @user_transaction = UserTransaction.new(user_transaction_params)

    respond_to do |format|
      if @user_transaction.save
        format.html { redirect_to @user_transaction, notice: 'User transaction was successfully created.' }
        format.json { render :show, status: :created, location: @user_transaction }
      else
        format.html { render :new }
        format.json { render json: @user_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_transactions/1
  # PATCH/PUT /user_transactions/1.json
  def update
    respond_to do |format|
      if @user_transaction.update(user_transaction_params)
        format.html { redirect_to @user_transaction, notice: 'User transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_transaction }
      else
        format.html { render :edit }
        format.json { render json: @user_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_transactions/1
  # DELETE /user_transactions/1.json
  def destroy
    @user_transaction.destroy
    respond_to do |format|
      format.html { redirect_to user_transactions_url, notice: 'User transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_transaction
      @user_transaction = UserTransaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_transaction_params
      params.require(:user_transaction).permit(:user_id, :transaction_type, :transaction_date, :transaction_amount)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_transactions_helper.rb
module UserTransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Transaction</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'style', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div id="container">
	  	<nav class="navbar black-bg header">
	  		<div id="container-fluid">
	  			<div class="navbar-header">
	  				<a class="navbar-brand logo font" href="#"><b>OneAdvanced</b></a>
	  			</div>
	  		</div>
	  			<div class="container-fluid">
	  				<ul class="nav navbar-nav navbar-left">
	  					<li class="hover">
						  </style>
	  						<a href="#">Link</a>
	  					</li>
	  				</ul>
	  			</div>
	  		
	  	</nav>
	</div>
<div class="wrapper" style="height: 800px"> 
            <div class="row mt">
                <div class="col-md-12">
                		<%= yield %>
                </div>
            </div>  
        
         </div>
  </body>
</html>

app/views/user_transactions/_form.html.erb
<%= form_with(model: user_transaction, local: true) do |form| %>
  <% if user_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_transaction.errors.count, "error") %> prohibited this user_transaction from being saved:</h2>

      <ul>
      <% user_transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :user_transaction_user_id %>
  </div>

  <div class="field">
    <%= form.label :transaction_type %>
    <%= form.text_field :transaction_type, id: :user_transaction_transaction_type %>
  </div>

  <div class="field">
    <%= form.label :transaction_date %>
    <%= form.datetime_select :transaction_date, id: :user_transaction_transaction_date %>
  </div>

  <div class="field">
    <%= form.label :transaction_amount %>
    <%= form.text_field :transaction_amount, id: :user_transaction_transaction_amount %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/user_transactions/edit.html.erb
<h1>Editing User Transaction</h1>

<%= render 'form', user_transaction: @user_transaction %>

<%= link_to 'Show', @user_transaction %> |
<%= link_to 'Back', user_transactions_path %>

app/views/user_transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>User Transactions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Transaction type</th>
      <th>Transaction date</th>
      <th>Transaction amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_transactions.each do |user_transaction| %>
      <tr>
        <td><%= user_transaction.user.name %></td>
        <td><%= user_transaction.transaction_type %></td>
        <td><%= user_transaction.transaction_date %></td>
        <td><%= user_transaction.transaction_amount %></td>
        <td><%= link_to 'Show', user_transaction %></td>
        <td><%= link_to 'Edit', edit_user_transaction_path(user_transaction) %></td>
        <td><%= link_to 'Destroy', user_transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Transaction', new_user_transaction_path %>

app/views/user_transactions/new.html.erb
<h1>New User Transaction</h1>

<%= render 'form', user_transaction: @user_transaction %>

<%= link_to 'Back', user_transactions_path %>

app/views/user_transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_transaction.user %>
</p>

<p>
  <strong>Transaction type:</strong>
  <%= @user_transaction.transaction_type %>
</p>

<p>
  <strong>Transaction date:</strong>
  <%= @user_transaction.transaction_date %>
</p>

<p>
  <strong>Transaction amount:</strong>
  <%= @user_transaction.transaction_amount %>
</p>

<%= link_to 'Edit', edit_user_transaction_path(@user_transaction) %> |
<%= link_to 'Back', user_transactions_path %>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true, html: {class: "form"}) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :user_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>